variable "aws_region" {
  description = "AWS region to deploy into."
  type        = string
  default     = "us-east-1"
}

variable "app_name" {
  description = "Name used for the ECR repository, ALB, ECS cluster/service, and IAM roles."
  type        = string
  default     = "apm-connectors"
}

variable "image_tag" {
  description = "Tag to build, push, and deploy."
  type        = string
  default     = "latest"
}

variable "cpu" {
  description = "Fargate task vCPU units, e.g. \"256\" = 0.25 vCPU. Must be a valid Fargate cpu/memory pair -- see AWS docs."
  type        = string
  default     = "256"
}

variable "memory" {
  description = "Fargate task memory in MB, e.g. \"512\". Must be a valid Fargate cpu/memory pair -- see AWS docs."
  type        = string
  default     = "512"
}

variable "desired_count" {
  description = "Number of running tasks."
  type        = number
  default     = 1
}

# -- Optional connector configuration -------------------------------------
# All optional and empty by default -- exactly like an unfilled-in local
# .env (see .env.example at the repo root): a connector left unset just
# means its /tools/* routes 503 until you configure it. Set the ones you
# want live in terraform.tfvars (never commit that file -- see
# terraform.tfvars.example).

variable "google_client_id" {
  description = "Google OAuth client ID, for Gmail + Calendar."
  type        = string
  default     = ""
}

variable "google_client_secret" {
  description = "Google OAuth client secret, for Gmail + Calendar. Stored as an SSM SecureString, never a plain env var."
  type        = string
  default     = ""
  sensitive   = true
}

variable "google_token_json" {
  description = "Full contents of a .google_token.json generated by the local interactive consent flow (see docs/running-locally.md) -- lets this headless deployment use an already-consented token instead of the browser flow, which can't run in a container. Optional: leave empty to fall back to google_client_id/secret at the interactive-flow code path (which will fail here with no browser -- only useful if you plan to supply this later). Stored as an SSM SecureString, never a plain env var."
  type        = string
  default     = ""
  sensitive   = true
}

variable "apm_excel_workbook_path" {
  description = "Local path (inside the container) to an Excel workbook, if using the local-file Excel connector. Usually left unset in favor of apm_excel_drive_file_id for a cloud deployment, since the container filesystem is ephemeral."
  type        = string
  default     = ""
}

variable "apm_excel_drive_file_id" {
  description = "Google Drive file id or name of the Excel workbook, if using the Drive-backed Excel connector."
  type        = string
  default     = ""
}

variable "salesforce_client_id" {
  description = "Salesforce Connected App consumer key, for the OAuth 2.0 Client Credentials Flow."
  type        = string
  default     = ""
}

variable "salesforce_client_secret" {
  description = "Salesforce Connected App consumer secret. Stored as an SSM SecureString, never a plain env var."
  type        = string
  default     = ""
  sensitive   = true
}

variable "salesforce_domain" {
  description = "Salesforce org domain (e.g. \"my-org-dev-ed.develop.my.salesforce.com\"), used to build the OAuth token URL and API base."
  type        = string
  default     = ""
}

variable "salesforce_api_version" {
  description = "Salesforce REST API version to call, e.g. \"v60.0\". Leave empty to use the connector's default (salesforce_tool.DEFAULT_API_VERSION)."
  type        = string
  default     = ""
}

variable "jira_base_url" {
  description = "Jira Cloud site base URL, e.g. \"https://yourcompany.atlassian.net\"."
  type        = string
  default     = ""
}

variable "jira_email" {
  description = "Atlassian account email the API token belongs to."
  type        = string
  default     = ""
}

variable "jira_api_token" {
  description = "Atlassian API token (Basic auth, paired with jira_email) -- create one at https://id.atlassian.com/manage-profile/security/api-tokens. Stored as an SSM SecureString, never a plain env var."
  type        = string
  default     = ""
  sensitive   = true
}

variable "database_url" {
  description = "Postgres connection string (\"postgresql://user:pass@host:port/dbname\") the apm_connectors API needs to run at all -- required, not optional: its status/audit StateStore and its LangGraph action-graph checkpointer are both Postgres-only (see src/apm_connectors/api/dependencies.py, mirroring apm_orchestrator's own Postgres-only case-graph checkpointer), with no file-backed/SQLite/in-memory fallback. The app fails fast at startup without it. Stored as an SSM SecureString, never a plain env var."
  type        = string
  sensitive   = true

  validation {
    condition     = length(var.database_url) > 0
    error_message = "database_url is required -- the apm_connectors API has no file-backed/in-memory fallback and refuses to start without a real Postgres connection string."
  }
}

variable "api_keys" {
  description = "\"name1:key1,name2:key2\" -- one entry per authenticated caller (an orchestrator service, a script, a human approver), same format as the local APM_API_KEYS env var (see .env.example). Optional: leave empty to keep this API's documented no-auth default (docs/api-contract.md's \"Auth is opt-in\") -- set this before anything beyond a network boundary you already trust can reach service_url. Stored as an SSM SecureString, never a plain env var, and only created/attached at all when set (like database_url above) -- unlike the other secrets, an \"unset\" placeholder value would be a real (if useless) key entry, not an empty value the app already treats as \"no auth configured\"."
  type        = string
  default     = ""
  sensitive   = true
}
